baseURL = "https://topaz.com/"
languageCode = "zh-cn"
title = "Navi Nowu's Portfolio"
#theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Navi Nowu test"
  description = "\"skidibi toilet rizz\" - S.T.E.V.E.N at some point "
  #github = "MeiK2333"
  #facebook = "MeiK2333"
  #twitter = "MeiK2333"
  #linkedin = "MeiK2333"
  #instagram = "MeiK2333"
  #tumblr = "MeiK2333"
  #email = "meik2333@gmail.com"
  #url = "https://meik2333.com"
  keywords = "blog, google analytics"
  # rss = true
  lastmod = true
  favicon = ""
  avatar = "images/avatar.jpeg"
  #headerIcon = ""
  location = "The Yggdrasil Space Explorer"
  #userStatusEmoji = "😀"
 # enableGitalk = true
  enableSearch = false



[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
